name: Fetch Feeds

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Dependencies
        run: yarn install
      - name: Run Script For Feeds
        run: yarn dev
      - name: Commit Changes
        run: |
          git config --global user.name "penrodlol"
          git config --global user.email "penrodlol@users.noreply.github.com"
          git add .
          git commit -m "🤖 Update Feed"
          git push
